name: Portfolio Check

on:
  push:
    branches:
      - main

jobs:
  check-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check main folders exist
        run: |
          test -d 01-book-api-v2
          test -d 02-auth-system-v1
          echo "All project folders exist 🚀"

      - name: Show structure
        run: ls -R

      - name: Success
        run: echo "Portfolio structure is valid ✅"
